"""Initial schema

Revision ID: 0569c7987c27
Revises: 
Create Date: 2026-01-19 01:15:07.754109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0569c7987c27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('single_use', sa.Boolean(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('tariff', sa.Float(), nullable=False),
    sa.Column('daytariff', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', 'hotel_manager', 'parking_meter', name='user_role'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('gates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gates_parking_lot_id'), 'gates', ['parking_lot_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_license_plate'), 'vehicles', ['license_plate'], unique=True)
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=16), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('channel', sa.Enum('registered', 'anonymous_driveup', 'company', 'hotel', name='reservation_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'cancelled', 'expired', 'completed', name='reservation_status'), nullable=False),
    sa.Column('quoted_cost', sa.Float(), nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=True),
    sa.Column('original_cost', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            (\n              channel = 'registered' AND user_id IS NOT NULL AND vehicle_id IS NOT NULL\n            )\n            OR\n            (\n              channel = 'anonymous_driveup' AND user_id IS NULL AND vehicle_id IS NULL AND license_plate IS NOT NULL\n            )\n            OR\n            (\n              channel IN ('company','hotel')\n            )\n            ", name='ck_reservation_channel_identity'),
    sa.CheckConstraint('planned_end > planned_start', name='ck_reservation_time_order'),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservation_lot_time', 'reservations', ['parking_lot_id', 'planned_start', 'planned_end'], unique=False)
    op.create_index(op.f('ix_reservations_discount_code_id'), 'reservations', ['discount_code_id'], unique=False)
    op.create_index(op.f('ix_reservations_license_plate'), 'reservations', ['license_plate'], unique=False)
    op.create_index(op.f('ix_reservations_parking_lot_id'), 'reservations', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    op.create_index(op.f('ix_reservations_vehicle_id'), 'reservations', ['vehicle_id'], unique=False)
    op.create_table('discount_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discount_code_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discount_code_id'], ['discount_codes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_redemptions_discount_code_id'), 'discount_redemptions', ['discount_code_id'], unique=False)
    op.create_index(op.f('ix_discount_redemptions_reservation_id'), 'discount_redemptions', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_discount_redemptions_user_id'), 'discount_redemptions', ['user_id'], unique=False)
    op.create_table('parking_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('license_plate', sa.String(length=16), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_gate_id', sa.Integer(), nullable=True),
    sa.Column('exit_gate_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'closed', 'void', 'violation', name='session_status'), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('exit_time IS NULL OR exit_time >= entry_time', name='ck_session_time_order'),
    sa.ForeignKeyConstraint(['entry_gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exit_gate_id'], ['gates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_sessions_license_plate'), 'parking_sessions', ['license_plate'], unique=False)
    op.create_index(op.f('ix_parking_sessions_parking_lot_id'), 'parking_sessions', ['parking_lot_id'], unique=False)
    op.create_index(op.f('ix_parking_sessions_reservation_id'), 'parking_sessions', ['reservation_id'], unique=False)
    op.create_index('ix_session_lot_entry', 'parking_sessions', ['parking_lot_id', 'entry_time'], unique=False)
    op.create_index('ix_session_plate_active_lookup', 'parking_sessions', ['license_plate', 'status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='payment_status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['parking_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_reservation_id'), 'payments', ['reservation_id'], unique=False)
    op.create_index(op.f('ix_payments_session_id'), 'payments', ['session_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_reservation_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_session_plate_active_lookup', table_name='parking_sessions')
    op.drop_index('ix_session_lot_entry', table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_reservation_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_parking_lot_id'), table_name='parking_sessions')
    op.drop_index(op.f('ix_parking_sessions_license_plate'), table_name='parking_sessions')
    op.drop_table('parking_sessions')
    op.drop_index(op.f('ix_discount_redemptions_user_id'), table_name='discount_redemptions')
    op.drop_index(op.f('ix_discount_redemptions_reservation_id'), table_name='discount_redemptions')
    op.drop_index(op.f('ix_discount_redemptions_discount_code_id'), table_name='discount_redemptions')
    op.drop_table('discount_redemptions')
    op.drop_index(op.f('ix_reservations_vehicle_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_parking_lot_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_license_plate'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_discount_code_id'), table_name='reservations')
    op.drop_index('ix_reservation_lot_time', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_license_plate'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_gates_parking_lot_id'), table_name='gates')
    op.drop_table('gates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('parking_lots')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    # ### end Alembic commands ###
